### ISSUE TITLE
after update the newest version,get error

### ISSUE THREAD

**Issue by gloddream** [atsushieno/cerbero#4] opened 2017-10-31 11:05 UTC
after update the newest version

get error：

armv7-a -Wl,--fix-cortex-a8 -pthread -pthread -Wl,-soname -Wl,libfluidsynth.so -o .libs/libfluidsynth.so
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_close: error: undefined reference to 'AAsset_close'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_open: error: undefined reference to 'AAssetManager_open'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_length: error: undefined reference to 'AAsset_getLength'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_position: error: undefined reference to 'AAsset_seek'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_safe_seek_by: error: undefined reference to 'AAsset_seek'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_safe_read: error: undefined reference to 'AAsset_read'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_read: error: undefined reference to 'AAsset_read'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function new_fluid_android_asset_stream_loader: error: undefined reference to 'AAssetManager_fromJava'
collect2: error: ld returned 1 exit status
Makefile:857: recipe for target 'libfluidsynth.la' failed
make[3]: *** [libfluidsynth.la] Error 1
make[3]: Leaving directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src'
Makefile:634: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth'

Recipe 'fluidsynth' failed at the build step 'compile'

**Comment by atsushieno** [comment] 2017-10-31 11:54
If you have outputs like this from cerbero:

     WARNING: Android NDK not found

You have to specify ANDROID_NDK_PATH environment variable first.

**Comment by gloddream** [comment] 2017-11-01 08:01
yes ， i have specified ANDROID_NDK_PATH environment variable first.
get errors:

ubuntu@ip-172-31-5-53:~/android-fluidsynth$ make
cd external/cerbero && CERBERO_LOCAL_CONFIG=../../custom.cbc ./cerbero-uninstalled -c config/cross-android-armv7.cbc build  fluidsynth
WARNING: Using configuration ../../custom.cbc
Building the following recipes: libiconv gnustl gettext libffi zlib glib fluidsynth
[(1/7) libiconv -> already built ]
[(2/7) gnustl -> already built ]
[(3/7) gettext -> already built ]
[(4/7) libffi -> already built ]
[(5/7) zlib -> already built ]
[(6/7) glib -> already built ]
[(7/7) fluidsynth -> fetch ]
-----> Step done
[(7/7) fluidsynth -> extract ]
-----> Step done
[(7/7) fluidsynth -> configure ]
-----> Step done
[(7/7) fluidsynth -> compile ]
Running command 'make'
make[1]: Entering directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth'
Making all in src
make[2]: Entering directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src'
make  all-am
make[3]: Entering directory '/home/ubuntu/android-fluidsynth/build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src'
/bin/bash ../libtool  --tag=CC   --mode=link arm-linux-androideabi-gcc -fuse-ld=gold  -DDEFAULT_SOUNDFONT=NULL  -O2 -fomit-frame-pointer -funroll-all-loops -finline-functions -Wall -W -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wstrict-prototypes -Winline -Wno-unused-parameter -Wno-cast-qual -version-info 6:2:5 -export-dynamic  -L/home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib --sysroot=/home/ubuntu/android-fluidsynth/external/cerbero/../../build/android-ndk-r15b/platforms/android-9/arch-arm -fPIC -no-canonical-prefixes -Wl,-no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-dynamic-linker,/system/bin/linker  -Wl,-z,nocopyreloc  -L/home/ubuntu/android-fluidsynth/external/cerbero/../../build/android-ndk-r15b/platforms/android-9/arch-arm/usr/lib  -llog -march=armv7-a -Wl,--fix-cortex-a8  -o libfluidsynth.la -rpath /home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib      drivers/libfluidsynth_la-fluid_opensles.lo       utils/libfluidsynth_la-fluid_conv.lo utils/libfluidsynth_la-fluid_hash.lo utils/libfluidsynth_la-fluid_list.lo utils/libfluidsynth_la-fluid_ringbuffer.lo utils/libfluidsynth_la-fluid_settings.lo utils/libfluidsynth_la-fluid_sys.lo sfloader/libfluidsynth_la-fluid_defsfont.lo sfloader/libfluidsynth_la-fluid_ramsfont.lo rvoice/libfluidsynth_la-fluid_adsr_env.lo rvoice/libfluidsynth_la-fluid_chorus.lo rvoice/libfluidsynth_la-fluid_iir_filter.lo rvoice/libfluidsynth_la-fluid_lfo.lo rvoice/libfluidsynth_la-fluid_rvoice.lo rvoice/libfluidsynth_la-fluid_rvoice_dsp.lo rvoice/libfluidsynth_la-fluid_rvoice_event.lo rvoice/libfluidsynth_la-fluid_rvoice_mixer.lo rvoice/libfluidsynth_la-fluid_rev.lo synth/libfluidsynth_la-fluid_chan.lo synth/libfluidsynth_la-fluid_event.lo synth/libfluidsynth_la-fluid_gen.lo synth/libfluidsynth_la-fluid_mod.lo synth/libfluidsynth_la-fluid_synth.lo synth/libfluidsynth_la-fluid_tuning.lo synth/libfluidsynth_la-fluid_voice.lo midi/libfluidsynth_la-fluid_midi.lo midi/libfluidsynth_la-fluid_midi_router.lo midi/libfluidsynth_la-fluid_seqbind.lo midi/libfluidsynth_la-fluid_seq.lo drivers/libfluidsynth_la-fluid_adriver.lo drivers/libfluidsynth_la-fluid_mdriver.lo drivers/libfluidsynth_la-fluid_aufile.lo bindings/libfluidsynth_la-fluid_cmd.lo bindings/libfluidsynth_la-fluid_ladspa.lo bindings/libfluidsynth_la-fluid_filerenderer.lo -lm           -L/home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib -lgthread-2.0 -pthread -lglib-2.0 -lintl   -lOpenSLES 
libtool: link: arm-linux-androideabi-gcc -fuse-ld=gold -shared  -fPIC -DPIC  drivers/.libs/libfluidsynth_la-fluid_opensles.o utils/.libs/libfluidsynth_la-fluid_conv.o utils/.libs/libfluidsynth_la-fluid_hash.o utils/.libs/libfluidsynth_la-fluid_list.o utils/.libs/libfluidsynth_la-fluid_ringbuffer.o utils/.libs/libfluidsynth_la-fluid_settings.o utils/.libs/libfluidsynth_la-fluid_sys.o sfloader/.libs/libfluidsynth_la-fluid_defsfont.o sfloader/.libs/libfluidsynth_la-fluid_ramsfont.o rvoice/.libs/libfluidsynth_la-fluid_adsr_env.o rvoice/.libs/libfluidsynth_la-fluid_chorus.o rvoice/.libs/libfluidsynth_la-fluid_iir_filter.o rvoice/.libs/libfluidsynth_la-fluid_lfo.o rvoice/.libs/libfluidsynth_la-fluid_rvoice.o rvoice/.libs/libfluidsynth_la-fluid_rvoice_dsp.o rvoice/.libs/libfluidsynth_la-fluid_rvoice_event.o rvoice/.libs/libfluidsynth_la-fluid_rvoice_mixer.o rvoice/.libs/libfluidsynth_la-fluid_rev.o synth/.libs/libfluidsynth_la-fluid_chan.o synth/.libs/libfluidsynth_la-fluid_event.o synth/.libs/libfluidsynth_la-fluid_gen.o synth/.libs/libfluidsynth_la-fluid_mod.o synth/.libs/libfluidsynth_la-fluid_synth.o synth/.libs/libfluidsynth_la-fluid_tuning.o synth/.libs/libfluidsynth_la-fluid_voice.o midi/.libs/libfluidsynth_la-fluid_midi.o midi/.libs/libfluidsynth_la-fluid_midi_router.o midi/.libs/libfluidsynth_la-fluid_seqbind.o midi/.libs/libfluidsynth_la-fluid_seq.o drivers/.libs/libfluidsynth_la-fluid_adriver.o drivers/.libs/libfluidsynth_la-fluid_mdriver.o drivers/.libs/libfluidsynth_la-fluid_aufile.o bindings/.libs/libfluidsynth_la-fluid_cmd.o bindings/.libs/libfluidsynth_la-fluid_ladspa.o bindings/.libs/libfluidsynth_la-fluid_filerenderer.o   -L/home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib -L/home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib -L/home/ubuntu/android-fluidsynth/external/cerbero/../../build/android-ndk-r15b/platforms/android-9/arch-arm/usr/lib -L/home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib -L/home/ubuntu/android-fluidsynth/external/cerbero/../../build/android-ndk-r15b/platforms/android-9/arch-arm/usr/lib -lm /home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib/libgthread-2.0.so /home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib/libglib-2.0.so /home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib/libintl.so /home/ubuntu/android-fluidsynth/external/cerbero/../../build/dist/android_armv7/lib/libiconv.so -llog -lc -lOpenSLES  -O2 --sysroot=/home/ubuntu/android-fluidsynth/external/cerbero/../../build/android-ndk-r15b/platforms/android-9/arch-arm -Wl,-no-undefined -Wl,-z -Wl,noexecstack -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--gc-sections -Wl,-dynamic-linker -Wl,/system/bin/linker -Wl,-z -Wl,nocopyreloc -march=armv7-a -Wl,--fix-cortex-a8 -pthread   -pthread -Wl,-soname -Wl,libfluidsynth.so -o .libs/libfluidsynth.so
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_close: error: undefined reference to 'AAsset_close'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_open: error: undefined reference to 'AAssetManager_open'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_length: error: undefined reference to 'AAsset_getLength'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_position: error: undefined reference to 'AAsset_seek'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_safe_seek_by: error: undefined reference to 'AAsset_seek'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_safe_read: error: undefined reference to 'AAsset_read'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function fluid_android_asset_stream_loader_read: error: undefined reference to 'AAsset_read'
sfloader/.libs/libfluidsynth_la-fluid_defsfont.o:fluid_defsfont.c:function new_fluid_android_asset_stream_loader: error: undefined reference to 'AAssetManager_fromJava'
collect2: error: ld returned 1 exit status
Makefile:857: recipe for target 'libfluidsynth.la' failed

**Comment by gloddream** [comment] 2017-11-01 08:02
almost about  : 
"function fluid_android_asset_stream_loader_*  "

**Comment by gloddream** [comment] 2017-11-01 09:25
i change commit to "2d5069f"， the build so  works well。
but still get error：
11-01 17:23:12.532 17940-17940/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Failed to open File **or Stream**: /sdcard/TimGM6mb.sf2
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Unable to open file "/sdcard/TimGM6mb.sf2"
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Couldn't load soundfont file: /sdcard/TimGM6mb.sf2
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Failed to load SoundFont "/sdcard/TimGM6mb.sf2"

**Comment by atsushieno** [comment] 2017-11-01 17:55
I cannot reproduce it locally, but I have an idea; you are using Android NDK r15b and it dropped support for Gingerbread. cerbero Android build still uses Gingerbread, so that might be problematic.

I just applied a local fix at de0dd29 so it might resolve your missing AAsset_* references issue.

**Comment by gloddream** [comment] 2017-11-02 05:15
i have a try。
do we support aws ec2 ubutun？

**Comment by gloddream** [comment] 2017-11-02 06:43
it doesnot work still.

ubuntu@ip-172-31-5-53:~/android-fluidsynth$ make prepare
cd external/cerbero && CERBERO_LOCAL_CONFIG=../../custom.cbc ./cerbero-uninstalled -c config/cross-android-armv7.cbc bootstrap
WARNING: Using configuration ../../custom.cbc
WARNING: No bootstrapper for the distro version android_jelly_bean
WARNING: No bootstrapper for the distro version ubuntu_xenial

**Comment by atsushieno** [comment] 2017-11-02 08:37
They are just warnings and don't tell the actual errors. What is the output like, when the build "stops" ?

**Comment by atsushieno** [comment] 2017-11-02 08:37
I'm running Ubuntu 17.04 and no one reported it works elsewhere.

**Comment by gloddream** [comment] 2017-11-02 09:08
the build libfluidsynth.so file works well。 (not use the newest version, the commit is "2d5069f")
_**but still get error when i use the so file ：**_

11-01 17:23:12.532 17940-17940/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Failed to open File or Stream: /sdcard/TimGM6mb.sf2
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Unable to open file "/sdcard/TimGM6mb.sf2"
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Couldn't load soundfont file: /sdcard/TimGM6mb.sf2
11-01 17:23:12.842 17940-17940/? E/fluidsynth: Failed to load SoundFont "/sdcard/TimGM6mb.sf2"

**_below is  jni  code:_**

/*
* Class:     com_libfluidsynth_jni_fluidsynth
* Method:    play
* Signature: (Ljava/lang/String;Ljava/lang/String;)V
*/
JNIEXPORT void JNICALL Java_com_libfluidsynth_jni_fluidsynth_play
(JNIEnv *env, jobject obj, jstring mid, jstring font)
{
        settings = new_fluid_settings();
        synth = new_fluid_synth(settings);
        const char *cfilename = (*env)->GetStringUTFChars(env,font, 0);

        //error happened
        **fluid_synth_sfload(synth, cfilename, 1);**

        (*env)->ReleaseStringUTFChars(env,font, cfilename);

        adriver = new_fluid_audio_driver(settings, synth);
        player = new_fluid_player(synth);

        const char *midf = (*env)->GetStringUTFChars(env, mid, 0);
        fluid_player_add(player, midf);
        (*env)->ReleaseStringUTFChars(env, mid, midf);
        fluid_player_play(player);

}

**Comment by atsushieno** [comment] 2017-11-02 09:23
I cannot care about old versions because the new code is EXACTLY to resolve that missing file issues (Android has no access to files within the package and has to resort to its own stream resolver). That's the whole point of https://github.com/atsushieno/cerbero/issues/5#issuecomment-340733288 .

**Comment by atsushieno** [comment] 2017-11-02 09:23
I'm not going to discuss the SAME problem on TWO distinct issues. Closing this one.

**Closed as completed by atsushieno** 2017-11-02 09:23 UTC

**Comment by gloddream** [comment] 2017-11-03 09:06
ok thanks
